import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@repo/ui/components/sonner";
import { ThemeProvider } from "@/providers/theme-provider";
import { cn } from "@repo/ui/lib/utils";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GestioNube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={cn(
          openSans.className,
          "font-sans antialiased scroll-smooth",
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen w-screen bg-muted/50 dark:bg-muted/20">
            {children}
            <Toaster position="top-center" closeButton />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
