name = "api"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"                                        # Replace with your Hyperdrive ID
localConnectionString = "postgres://postgres:password@127.0.0.1:5432/inventia"
